name: Publish Docker image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: swiato
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./complexapp
          file: ./complexapp/Dockerfile
          push: true
          tags: swiato/ci-cd:latest